### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by john-shepherdson** [cessda/cessda.cmv#174]
DOIs:
Core 10.5281/zenodo.10013270
Server 10.5281/zenodo.10013426
Documentation N/A

Release checklist: https://docs.google.com/spreadsheets/d/1dmku1ZfUVifCjjNtHuNO1gK-qYyBVO3MlrkBVnKoNoI/edit#gid=343455232

Release report: https://docs.google.com/document/d/1d7HtkMSAwW0M6YK9_gousyr6lxc4Ucfd78Yck84UmxE/edit

```[tasklist]
### Tasks
- [ ] https://github.com/cessda/cessda.cmv.core/issues/163
- [ ] https://github.com/cessda/cessda.cmv.server/issues/160
- [ ] https://github.com/cessda/cessda.cmv.documentation/issues/36
- [ ] https://github.com/cessda/cessda.cmv.server/issues/161
```

**Comment by matthew-morris-cessda** [comment]
The release version will be 2.0.0 due to breaking changes to CMV Core's API

**Comment by matthew-morris-cessda** [comment]
CMV Core 2.0.0 has been released

**Comment by matthew-morris-cessda** [comment]
Ready to release

**Comment by matthew-morris-cessda** [comment]
CMV Server 2.0.0 has been released
